### ISSUE TITLE
Code for Figure 2e visualization

### ISSUE THREAD

**Issue by aitortxo10** [aertslab/scenicplus_analyses#2]
Hello everyone,

Amazing job and thank you for providing this tool! 

I was trying to apply SCENIC+ onto some some of our data, and while it works without major issues with the new snakemake update, I was having some issues regarding visualization. I followed the pbmc tutorial from the docs for the downstream analysis, but getting the networks visualization for 2-3 regulons is proving to be challenging since a hairball of numbers is always present somewhere on the graph. Thus, I was trying to produce an image similar to your figure 2e, but I could not find the corresponding code since figure 2e is related to the overlap of regions in the code uploaded. I also saw that you export the networks for visualization in R, but I could not find further code regarding the visualization.

![image](https://github.com/aertslab/scenicplus_analyses/assets/74412029/91796b49-7c04-474e-a40f-e05111c8790e)

Could the code for figure 2e be placed in any other folder/repository which I may have missed? Otherwise, could it be possible to get an idea of the workflow and R package used for this figure?

Thank you in advance

**Comment by SeppeDeWinter** [comment]
Hi @aitortxo10 

Unfortunately, this figure was made largely manually by exporting the network and editing its layout in cytoscape.
We don't have code to produce the layout of this plot.

All the best,

Seppe

**Comment by aitortxo10** [comment]
Hello @SeppeDeWinter,

Thank you for your answer! Given that the layout was edited in cytoscape, I will close the issue.

Thank you for your help,
Aitor
